
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/canvas?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true